name: Django CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Check Python version
        run: python --version
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Check Syntax
        run: pflake8 --count .
      
      - name: Run Migrations
        run: python manage.py migrate
      
      - name: Run Test
        run: python manage.py test

  deploy-job:
    runs-on: ubuntu-latest
    needs: [health-check-job]
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USERNAME }}
        REMOTE_PORT: ${{ secrets.VPS_PORT }}
        TARGET: "${{ secrets.VPS_APPS_BASE_PATH }}/django-github-deploy"
        # ARGS: "-rltgoDzvO"
        EXCLUDE: "
          /node_modules/,
          .git/
        "

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        PORT: ${{ secrets.VPS_PORT }}
        KEY: ${{ secrets.VPS_SSH_KEY }}
        script: ls ${{ secrets.VPS_APPS_BASE_PATH }}/django-github-deploy